name: UT Job

on:
  workflow_call:
    inputs:
      CP_DOCKER_IMG:
        required: true
        type: string
      pr_id:
        required: true
        type: string
      runs_on_arch:
        required: true
        type: string

jobs:
  JOB_Compile:
    name: Test
    select: selected_by_default
    needs: [ ]
    runs-on: [ self-hosted, ipv4, arm, cpu=30 ]
    container:
      image: ${{ inputs.CP_DOCKER_IMG }}
    steps:
      - name: Checkout repository with pre merge
        uses: checkout
        with:
          repository: ${{atomgit.repositoryurl}}
          ref: refs/merge-requests/${{ inputs.pr_id }}/merge

      - name: Execute_shell
        run: |-
          WORKSPACE=${{atomgit.workspace}}
          arch=`uname -m`
          endpoint='obs.cn-north-4.myhuaweicloud.com'
          obs_base_path="obs://mindie-pr/monitor/ascend/MindIE-SD"
          python_3rdparty_path=/opt/buildtools/python-3.11.4/lib/python3.11/site-packages
          export PYTHONPATH=${python_3rdparty_path}:$PYTHONPATH
          export PATH=/opt/buildtools/python-3.11.4/bin:$PATH

          pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements.txt

          cd ${WORKSPACE}
          relative_path=${{ inputs.pr_id }}/$(uname -i)
          obs_path_no_prefix="${obs_base_path#obs://}"
          bucket="${obs_path_no_prefix%%/*}"
          rest_path="${obs_path_no_prefix#*/}"
          whl_name="motor-0.1.0-py3-none-any.whl"
          https_url="https://${bucket}.${endpoint}/${rest_path}/${relative_path}/${whl_name}"

          mkdir -p ./dist
          set +e
          wget --no-check-certificate -q -O "./dist/${whl_name}" "${https_url}"
          wget_ret=$?
          set -e

          if [ ${wget_ret} -ne 0 ]; then
              echo "==== wget failed(code:${wget_ret}), trigger build.sh local compile"
              sh build.sh
          fi
          ls ./dist/

          cd ${WORKSPACE}/tests
          bash run_tests.sh
          exit_status=$?

          set -e
          if [ "${exit_status}" -eq 0 ]; then
              echo "UT passed"
          else
              echo "UT failed, test script return code: ${exit_status}"
              exit ${exit_status}
          fi
